# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d9aa4e299ccb21484413b932e76fc9e5"
name = "ICTECHM2SMigrator"
application_url = "https://wheat-raised-upgrading-cardiac.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
uri = "/webhooks/compliance"
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations,write_customers,write_orders,read_publications,write_publications,read_online_store_navigation,write_online_store_navigation,write_files,write_discounts,read_discounts,read_translations,write_translations,read_locales,read_markets,write_markets"

[auth]
redirect_urls = [
  "https://wheat-raised-upgrading-cardiac.trycloudflare.com/auth/shopify/callback"
]
